// Builds the bookmarklet from src/psa.js. Needs terser (a dev dependency):
//
//   npm ci
//   npm run build
//
// Writes dist/psa.min.js (plain script, used by the test page), dist/bookmarklet.txt (the javascript: URL),
// index.html, the install page (from src/install.html) that GitHub Pages serves at the site root, and
// dist/firefox/, the Firefox extension (from src/firefox/ plus src/psa.js, left readable for review).
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { minify } from 'terser';

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, 'dist');
const source = readFileSync(join(root, 'src', 'psa.js'), 'utf8');
const template = readFileSync(join(root, 'src', 'install.html'), 'utf8');
const version = (source.match(/const VERSION = '([^']+)'/) || [])[1];
if (!version) throw new Error("src/psa.js has no `const VERSION = '…'` line");

// Terser leaves template literals alone, so squeeze the panel's CSS first: collapse whitespace and drop it
// around { } ; : , (the CSS has no descendant selectors followed by a pseudo-class, where a space matters).
const squeezeCss = (css) =>
  css
    .replace(/\s+/g, ' ')
    .replace(/\s*([{};:,])\s*/g, '$1')
    .replace(/;}/g, '}')
    .trim();
const prepared = source.replace(/const CSS = `([^`]*)`;/, (all, css) => 'const CSS = `' + squeezeCss(css) + '`;');

// Renames the bookmarklet's internal names, removes whitespace and shortens syntax. Text and property
// names are untouched, so saved settings and window.__speedCtl stay the same. play() keeps its name
// because it replaces HTMLMediaElement.prototype.play while the panel is open. Strings use single quotes,
// which a javascript: URL carries as they are, where each double quote would cost three characters (%22).
// __PSA_EXTENSION__ is only defined inside the Firefox extension, so the bookmarklet drops that code.
const minified = await minify(prepared, {
  ecma: 2020,
  compress: { passes: 3, keep_fnames: /^play$/, global_defs: { __PSA_EXTENSION__: null } },
  mangle: { keep_fnames: /^play$/ },
  format: { comments: false, quote_style: 1 },
});
// Ending on `void 0` guarantees the javascript: URL evaluates to undefined; a string result would replace the page.
const code = minified.code.replace(/;?$/, ';void 0;');

// Throws with a line number if minifying ever breaks the syntax.
new vm.Script(code, { filename: 'psa.min.js' });

// Percent-encode only what a javascript: URL or the install page's href="…" can't carry as-is:
// % (it starts an escape), whitespace, # (fragment), " and & (HTML), and non-ASCII characters.
const encodeForUrl = (text) => text.replace(/[%\s#"&]|[^\x20-\x7e]/gu, (c) => encodeURIComponent(c));
const bookmarklet = 'javascript:' + encodeForUrl(code);

// The bookmarklet goes in last, so its %XX escapes are never mistaken for placeholders.
const install = template
  .replace(/<!-- Template[^\n]*-->\n/, '')
  .replaceAll('%SIZE%', code.length.toLocaleString('en'))
  .replaceAll('%VERSION%', version)
  .replaceAll('%BOOKMARKLET%', () => bookmarklet);

mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'psa.min.js'), code + '\n');
writeFileSync(join(dist, 'bookmarklet.txt'), bookmarklet + '\n');
writeFileSync(join(root, 'index.html'), install);

// The Firefox extension: src/psa.js wrapped as startPsa(extension), started by page.js, all in one function
// so the page's globals only gain window.__speedCtl, as with the bookmarklet.
const firefoxSrc = join(root, 'src', 'firefox');
const firefox = join(dist, 'firefox');
mkdirSync(firefox, { recursive: true });
const page = readFileSync(join(firefoxSrc, 'page.js'), 'utf8');
const extensionScript =
  '// Generated by build.mjs from src/psa.js and src/firefox/page.js. Edit those instead.\n' +
  '(() => {\n' +
  "  'use strict';\n\n" +
  '  function startPsa(__PSA_EXTENSION__) {\n' +
  source +
  '  }\n\n' +
  page +
  '})();\n';
new vm.Script(extensionScript, { filename: 'firefox/psa.js' });
writeFileSync(join(firefox, 'psa.js'), extensionScript);
writeFileSync(
  join(firefox, 'manifest.json'),
  readFileSync(join(firefoxSrc, 'manifest.json'), 'utf8').replace('%VERSION%', version)
);
['background.js', 'bridge.js', 'defaults.js', 'options.html', 'options.js', 'icon.svg'].forEach((name) =>
  copyFileSync(join(firefoxSrc, name), join(firefox, name))
);

console.log(`Built PSA ${version}: ${code.length} chars of code, ${bookmarklet.length} chars as a URL.`);
